websocket-client 0.49
- 0.50.0

  - fixed pong before ping (#461)
  - pass proper arguments to method callbacks (#462)

- 0.49.0

  - WebSocketApp class to make it inheritable (#442)
  - Add option to disable sending the Origin header (#459)
  - Websocket.close() meaning of "close status: XXXXX" (#414)
  - Enable multithreading protection with ping_interval (#448)
  - reset WebsocketApp.sock (#450)
  - websocket.enableTrace not working (#455)
  - AttributeError: 'module' object has no attribute 'NullHandler' (#443)
  - WebSocketBadStatusException "not enough arguments for format string" (#454)
  - handshake should deal with None in headers (#432)

- 0.48.0

  - Add NullHandler to logger to fix python 2 issue. (#400)
  - Fix the issue that websocket status message may not present (#403)
  - Socket error not raised in nested try except in python2 (#408)
  - Load system default certificates if none are given (#415)
  - Fix waiting forever on ping/pong timeout (#411)
  - socks5 via pysocks support (#417)
  - v0.47.0 breaks ability to stop stream with `run_forever` (#410)
- _http.py: fix windows proxy error due to socktype (#427)